package com.oneplatform.user.controller;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.jeesuite.common.util.AssertUtil;
import com.jeesuite.common.util.BeanUtils;
import com.jeesuite.mybatis.plugin.pagination.Page;
import com.jeesuite.springweb.model.WrapperResponse;
import com.jeesuite.security.client.LoginContext;
import com.oneplatform.base.model.IdParam;

import com.oneplatform.user.dto.param.UserAssetLogQueryParam;
import com.oneplatform.user.dao.entity.UserAssetLogEntity;
import com.oneplatform.user.dto.param.UserAssetLogParam;
import com.oneplatform.user.service.UserAssetLogService;

import io.swagger.annotations.ApiOperation;

/**
 * generated by www.jeesuite.com
 */
@Controller
@RequestMapping("/userAssetLog")
public class UserAssetLogController {

    private @Autowired UserAssetLogService userAssetLogService;
	
	@ApiOperation(value = "分页查询")
	@RequestMapping(value = "list", method = RequestMethod.POST)
    public @ResponseBody Page<UserAssetLogEntity> pageQueryUserAssetLogs(@RequestBody UserAssetLogQueryParam param) {
		Page<UserAssetLogEntity> page = userAssetLogService.pageQuery(param,param);
		return page;
	}
	
	@ApiOperation(value = "按id查询")
	@RequestMapping(value = "{id}", method = RequestMethod.GET)
    public @ResponseBody WrapperResponse<UserAssetLogEntity> getById(@PathVariable("id") int id) {
		UserAssetLogEntity entity = userAssetLogService.findUserAssetLogById(id);
		return new WrapperResponse<>(entity);
	}
	
	@ApiOperation(value = "新增")
	@RequestMapping(value = "add", method = RequestMethod.POST)
    public @ResponseBody WrapperResponse<String> addUserAssetLog(@RequestBody UserAssetLogParam param) {
		UserAssetLogEntity entity = BeanUtils.copy(param, UserAssetLogEntity.class);
		//entity.setCreatedAt(new Date());
		//entity.setCreatedBy(LoginContext.getIntFormatUserId());
		userAssetLogService.addUserAssetLog(entity);
		
		return new WrapperResponse<>();
	}
	
	@ApiOperation(value = "更新")
	@RequestMapping(value = "update", method = RequestMethod.POST)
    public @ResponseBody WrapperResponse<String> updateUserAssetLog(@RequestBody UserAssetLogParam param) {
		UserAssetLogEntity entity = BeanUtils.copy(param, UserAssetLogEntity.class);
		//entity.setUpdatedAt(new Date());
		//entity.setUpdatedBy(LoginContext.getIntFormatUserId());
		userAssetLogService.updateUserAssetLog(entity);
		
		return new WrapperResponse<>();
	}
	
	@ApiOperation(value = "删除")
	@RequestMapping(value = "delete/{id}", method = RequestMethod.POST)
    public @ResponseBody WrapperResponse<String> deleteUserAssetLog(@RequestBody IdParam param) {
		userAssetLogService.deleteUserAssetLog(param.getId());
		return new WrapperResponse<>();
	}
	
	
}
