package com.oneplatform.user.dao.mapper;

import java.util.List;
import java.util.Map;

import com.jeesuite.mybatis.plugin.pagination.annotation.Pageable;
import com.oneplatform.user.dao.entity.UserAssetLogEntity;
import com.oneplatform.user.dto.param.UserAssetLogQueryParam;
import com.jeesuite.mybatis.core.BaseMapper;

/**
 * generated by www.jeesuite.com
 */
public interface UserAssetLogEntityMapper extends BaseMapper<UserAssetLogEntity,Integer> {

    @Pageable
	List<UserAssetLogEntity> findListByQueryParam(UserAssetLogQueryParam param);
}