package com.oneplatform.user.dao.mapper;

import java.util.List;
import java.util.Map;

import com.jeesuite.mybatis.plugin.pagination.annotation.Pageable;
import com.oneplatform.user.dao.entity.UserAssetsEntity;
import com.oneplatform.user.dto.param.UserAssetsQueryParam;
import com.jeesuite.mybatis.core.BaseMapper;

/**
 * generated by www.jeesuite.com
 */
public interface UserAssetsEntityMapper extends BaseMapper<UserAssetsEntity,Integer> {

    @Pageable
	List<UserAssetsEntity> findListByQueryParam(UserAssetsQueryParam param);
}