package com.oneplatform.user.dao.mapper;

import java.util.List;
import java.util.Map;

import com.jeesuite.mybatis.plugin.pagination.annotation.Pageable;
import com.oneplatform.user.dao.entity.UserInfoEntity;
import com.oneplatform.user.dto.param.UserInfoQueryParam;
import com.jeesuite.mybatis.core.BaseMapper;

/**
 * generated by www.jeesuite.com
 */
public interface UserInfoEntityMapper extends BaseMapper<UserInfoEntity,Integer> {

    @Pageable
	List<UserInfoEntity> findListByQueryParam(UserInfoQueryParam param);
}