package com.oneplatform.organisation.service;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.jeesuite.common.util.BeanUtils;
import com.jeesuite.mybatis.plugin.pagination.Page;
import com.jeesuite.mybatis.plugin.pagination.PageExecutor;
import com.jeesuite.mybatis.plugin.pagination.PageExecutor.PageDataLoader;
import com.jeesuite.mybatis.plugin.pagination.PageParams;
import com.oneplatform.base.exception.AssertUtil;
import com.oneplatform.base.model.PageResult;
import com.oneplatform.organisation.dao.entity.EmployeeEntity;
import com.oneplatform.organisation.dao.mapper.EmployeeEntityMapper;

/**
 * generated by www.jeesuite.com
 */
@Service
public class EmployeeService {

	@Autowired
	private EmployeeEntityMapper employeeMapper;

	public void addEmployee(EmployeeEntity entity) {
		employeeMapper.insertSelective(entity);
	}

	public void updateEmployee(EmployeeEntity entity) {
		EmployeeEntity originEntity = employeeMapper.selectByPrimaryKey(entity.getId());
		AssertUtil.notNull(originEntity);
		BeanUtils.copy(entity, originEntity);
		employeeMapper.updateByPrimaryKey(originEntity);
	}
	
	public void deleteEmployee(Integer id) {
		employeeMapper.deleteByPrimaryKey(id);
	}
	
	public EmployeeEntity findEmployeeById(Integer id){
		EmployeeEntity entity = employeeMapper.selectByPrimaryKey(id);
		AssertUtil.notNull(entity);
		return entity;
	}
	
    public PageResult<EmployeeEntity> pageQuery(PageParams pageParam,Map<String, Object> conditions){
		Page<EmployeeEntity> page = PageExecutor.pagination(pageParam, new PageDataLoader<EmployeeEntity>() {
			@Override
			public List<EmployeeEntity> load() {
				return employeeMapper.findByParam(conditions);
			}
		});
		return new PageResult<EmployeeEntity>(page.getPageNo(), page.getPageSize(), page.getTotal(), page.getData());
	}

}
