package com.oneplatform.organisation.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.jeesuite.common.util.BeanUtils;
import com.oneplatform.base.exception.AssertUtil;
import com.oneplatform.organisation.dao.entity.PositionEntity;
import com.oneplatform.organisation.dao.mapper.PositionEntityMapper;

/**
 * generated by www.jeesuite.com
 */
@Service
public class PositionsService {

	@Autowired
	private PositionEntityMapper positionsMapper;

	public void addPositions(PositionEntity entity) {
		positionsMapper.insertSelective(entity);
	}

	public void updatePositions(PositionEntity entity) {
		PositionEntity originEntity = positionsMapper.selectByPrimaryKey(entity.getId());
		AssertUtil.notNull(originEntity);
		BeanUtils.copy(entity, originEntity);
		positionsMapper.updateByPrimaryKey(originEntity);
	}
	
	public void deletePositions(Integer id) {
		positionsMapper.deleteByPrimaryKey(id);
	}
	
	public PositionEntity findPositionsById(Integer id){
		PositionEntity entity = positionsMapper.selectByPrimaryKey(id);
		AssertUtil.notNull(entity);
		return entity;
	}


	public List<PositionEntity> findAll(){
		return positionsMapper.selectAll();
	}
}
