package com.oneplatform.user.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.jeesuite.common.util.AssertUtil;
import com.oneplatform.user.dao.entity.UserAssetsEntity;
import com.oneplatform.user.dao.mapper.UserAssetsEntityMapper;

/**
 * generated by www.jeesuite.com
 */
@Service
public class UserAssetsService {

	@Autowired
	private UserAssetsEntityMapper userAssetsMapper;

	
	public UserAssetsEntity findUserAssetsById(Integer id){
		UserAssetsEntity entity = userAssetsMapper.selectByPrimaryKey(id);
		AssertUtil.notNull(entity);
		return entity;
	}
	
    public List<UserAssetsEntity> findUserAssetsUserId(Integer userId){
		return userAssetsMapper.findListByUserId(userId);
	}

}
