package com.oneplatform.cms.dto.param;

import io.swagger.annotations.ApiModelProperty;

/**
 * generated by www.jeesuite.com
 */
public class ArticleParam{

    @ApiModelProperty("属性名")
    private Integer id;
    
    @ApiModelProperty("标题")
    private String title;
    
    @ApiModelProperty("属性名")
    private String cover;
    
    @ApiModelProperty("属性名")
    private String summary;
    
    @ApiModelProperty("内容")
    private String content;
    
    @ApiModelProperty("属性名")
    private Integer categoryId;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }
    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    
}