package com.oneplatform.cms.dto.param;

import com.jeesuite.mybatis.plugin.pagination.PageParams;

/**
 * generated by www.jeesuite.com
 */
public class CmsArticleQueryParam  extends PageParams {

    private String title;
    private String cover;
    private String summary;
    private String content;
    private Integer categoryId;
    private Integer viewCount;
    private Integer commentCount;
    private Integer likeCount;
    private Boolean audited;
    private Integer createdBy;
    private java.util.Date createdAt;
    private Integer updatedBy;
    private java.util.Date updatedAt;

   public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
   public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }
   public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }
   public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
   public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
   public Integer getViewCount() {
        return viewCount;
    }

    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }
   public Integer getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }
   public Integer getLikeCount() {
        return likeCount;
    }

    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
   public Boolean getAudited() {
        return audited;
    }

    public void setAudited(Boolean audited) {
        this.audited = audited;
    }
   public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
   public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
   public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
   public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}