package com.oneplatform.user.dao.entity;

import com.jeesuite.mybatis.core.BaseEntity;
import javax.persistence.*;

/**
 * generated by www.jeesuite.com
 */
@Table(name = "USER_INFO")
public class UserInfoEntity extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;
    
    /**
    * @return mobile 
    */
    @Column(name = "mobile")
    private String mobile;
    
    /**
    * @return email 
    */
    @Column(name = "email")
    private String email;
    
    /**
    * @return realname 
    */
    @Column(name = "realname")
    private String realname;
    
    /**
    * @return nickname 
    */
    @Column(name = "nickname")
    private String nickname;
    
    /**
    * @return avatar 
    */
    @Column(name = "avatar")
    private String avatar;
    
    /**
    * @return gender 
    */
    @Column(name = "gender")
    private String gender;
    
    /**
    * @return birthday 
    */
    @Column(name = "birthday")
    private java.util.Date birthday;
    
    /**
    * @return areaId 所在行政区域ID
    */
    @Column(name = "area_id")
    private Integer areaId;
    
    /**
    * @return location 所在地
    */
    @Column(name = "location")
    private String location;
    
    /**
    * @return mobileVerified 
    */
    @Column(name = "mobile_verified")
    private Boolean mobileVerified;
    
    /**
    * @return deleted 
    */
    @Column(name = "deleted")
    private Boolean deleted;
    
    /**
    * @return enabled 
    */
    @Column(name = "enabled")
    private Boolean enabled;
    
    /**
    * @return createdAt 
    */
    @Column(name = "created_at")
    private java.util.Date createdAt;
    
    /**
    * @return lastLoginAt 
    */
    @Column(name = "last_login_at")
    private java.util.Date lastLoginAt;
    
    /**
    * @return updatedAt 
    */
    @Column(name = "updated_at")
    private java.util.Date updatedAt;
    

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }
    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }
    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }
    public Integer getAreaId() {
        return areaId;
    }

    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
    public Boolean getMobileVerified() {
        return mobileVerified;
    }

    public void setMobileVerified(Boolean mobileVerified) {
        this.mobileVerified = mobileVerified;
    }
    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
    public java.util.Date getLastLoginAt() {
        return lastLoginAt;
    }

    public void setLastLoginAt(java.util.Date lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}