package com.oneplatform.user.dao.entity;

import com.jeesuite.mybatis.core.BaseEntity;
import javax.persistence.*;

/**
 * generated by www.jeesuite.com
 */
@Table(name = "USER_ASSETS")
public class UserAssetsEntity extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;
    
    /**
    * @return userId 余额，平台币，积分
    */
    @Column(name = "user_id")
    private Integer userId;
    
    /**
    * @return available 可用的
    */
    @Column(name = "available")
    private java.math.BigDecimal available;
    
    /**
    * @return frozen 冻结的
    */
    @Column(name = "frozen")
    private java.math.BigDecimal frozen;
    
    /**
    * @return sign 
    */
    @Column(name = "sign")
    private String sign;
    
    /**
    * @return enabled 
    */
    @Column(name = "enabled")
    private Boolean enabled;
    
    /**
    * @return createdAt 
    */
    @Column(name = "created_at")
    private java.util.Date createdAt;
    
    /**
    * @return updatedAt 
    */
    @Column(name = "updated_at")
    private java.util.Date updatedAt;
    

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public java.math.BigDecimal getAvailable() {
        return available;
    }

    public void setAvailable(java.math.BigDecimal available) {
        this.available = available;
    }
    public java.math.BigDecimal getFrozen() {
        return frozen;
    }

    public void setFrozen(java.math.BigDecimal frozen) {
        this.frozen = frozen;
    }
    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }
    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}