package com.oneplatform.cms.dao.mapper;

import java.util.List;

import com.jeesuite.mybatis.core.BaseMapper;
import com.jeesuite.mybatis.plugin.pagination.annotation.Pageable;
import com.oneplatform.cms.dao.entity.ArticleEntity;
import com.oneplatform.cms.dto.param.ArticleQueryParam;

/**
 * generated by www.jeesuite.com
 */
public interface ArticleEntityMapper extends BaseMapper<ArticleEntity,Integer> {

    @Pageable
	List<ArticleEntity> findListByQueryParam(ArticleQueryParam param);
}