package com.oneplatform.cms.dao.mapper;

import java.util.List;
import java.util.Map;

import com.jeesuite.mybatis.plugin.pagination.annotation.Pageable;
import com.oneplatform.cms.dao.entity.CmsArticleEntity;
import com.oneplatform.cms.dto.param.CmsArticleQueryParam;
import com.jeesuite.mybatis.core.BaseMapper;

/**
 * generated by www.jeesuite.com
 */
public interface CmsArticleEntityMapper extends BaseMapper<CmsArticleEntity,Integer> {

    @Pageable
	List<CmsArticleEntity> findListByQueryParam(CmsArticleQueryParam param);
}