package com.oneplatform.user.dto.param;

import com.jeesuite.mybatis.plugin.pagination.PageParams;

/**
 * generated by www.jeesuite.com
 */
public class UserAssetsQueryParam  extends PageParams {

    private Integer userId;
    private java.math.BigDecimal available;
    private java.math.BigDecimal frozen;
    private String sign;
    private Boolean enabled;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

   public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
   public java.math.BigDecimal getAvailable() {
        return available;
    }

    public void setAvailable(java.math.BigDecimal available) {
        this.available = available;
    }
   public java.math.BigDecimal getFrozen() {
        return frozen;
    }

    public void setFrozen(java.math.BigDecimal frozen) {
        this.frozen = frozen;
    }
   public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }
   public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
   public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
   public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}