package com.oneplatform.user.dto.param;

import io.swagger.annotations.ApiModelProperty;

/**
 * generated by www.jeesuite.com
 */
public class UserAssetsParam{

    @ApiModelProperty("属性名")
    private Integer id;
    
    @ApiModelProperty("余额，平台币，积分")
    private Integer userId;
    
    @ApiModelProperty("可用的")
    private java.math.BigDecimal available;
    
    @ApiModelProperty("冻结的")
    private java.math.BigDecimal frozen;
    
    @ApiModelProperty("属性名")
    private String sign;
    
    @ApiModelProperty("属性名")
    private Boolean enabled;
    
    @ApiModelProperty("属性名")
    private java.util.Date createdAt;
    
    @ApiModelProperty("属性名")
    private java.util.Date updatedAt;
    

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public java.math.BigDecimal getAvailable() {
        return available;
    }

    public void setAvailable(java.math.BigDecimal available) {
        this.available = available;
    }
    public java.math.BigDecimal getFrozen() {
        return frozen;
    }

    public void setFrozen(java.math.BigDecimal frozen) {
        this.frozen = frozen;
    }
    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }
    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}