package com.oneplatform.user.dto.param;

import com.jeesuite.mybatis.plugin.pagination.PageParams;

/**
 * generated by www.jeesuite.com
 */
public class UserAssetLogQueryParam  extends PageParams {

    private Integer userId;
    private String tradeName;
    private String assetType;
    private String subType;
    private String tradeType;
    private java.math.BigDecimal amount;
    private java.math.BigDecimal currentAvailable;
    private java.math.BigDecimal currentFrozen;
    private String sign;
    private String memo;
    private Boolean hidden;
    private java.util.Date tradeAt;
    private String operator;

   public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
   public String getTradeName() {
        return tradeName;
    }

    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }
   public String getAssetType() {
        return assetType;
    }

    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }
   public String getSubType() {
        return subType;
    }

    public void setSubType(String subType) {
        this.subType = subType;
    }
   public String getTradeType() {
        return tradeType;
    }

    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }
   public java.math.BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
   public java.math.BigDecimal getCurrentAvailable() {
        return currentAvailable;
    }

    public void setCurrentAvailable(java.math.BigDecimal currentAvailable) {
        this.currentAvailable = currentAvailable;
    }
   public java.math.BigDecimal getCurrentFrozen() {
        return currentFrozen;
    }

    public void setCurrentFrozen(java.math.BigDecimal currentFrozen) {
        this.currentFrozen = currentFrozen;
    }
   public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }
   public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }
   public Boolean getHidden() {
        return hidden;
    }

    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }
   public java.util.Date getTradeAt() {
        return tradeAt;
    }

    public void setTradeAt(java.util.Date tradeAt) {
        this.tradeAt = tradeAt;
    }
   public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }
}