package com.oneplatform.organisation.dto.param;

import io.swagger.annotations.ApiModelProperty;

/**
 * generated by www.jeesuite.com
 */
public class DepartmentParam{

    @ApiModelProperty("属性名")
    private Integer id;
    
    @ApiModelProperty("属性名")
    private String name;
    
    @ApiModelProperty("属性名")
    private String telephone;
    
    @ApiModelProperty("属性名")
    private Integer companyId;
    
    @ApiModelProperty("联系人员工ID")
    private Integer contactEmployeeId;
    
    @ApiModelProperty("联系人")
    private String contactName;
    

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Integer getContactEmployeeId() {
        return contactEmployeeId;
    }

    public void setContactEmployeeId(Integer contactEmployeeId) {
        this.contactEmployeeId = contactEmployeeId;
    }
    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

}