package com.oneplatform.organisation.dto.param;

import io.swagger.annotations.ApiModelProperty;

/**
 * generated by www.jeesuite.com
 */
public class EmployeeParam{

    @ApiModelProperty("属性名")
    private Integer id;
    
    @ApiModelProperty("属性名")
    private String name;
    
    @ApiModelProperty("属性名")
    private String email;
    
    @ApiModelProperty("属性名")
    private String mobile;
    
    @ApiModelProperty("属性名")
    private String address;
    
    @ApiModelProperty("联系人")
    private String contactName;
    
    @ApiModelProperty("联系人电话")
    private String contactTel;
    
    @ApiModelProperty("属性名")
    private Integer positionId;
    
    @ApiModelProperty("属性名")
    private Integer departmentId;
    
    @ApiModelProperty("属性名")
    private java.util.Date joinedAt;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getContactTel() {
        return contactTel;
    }

    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }
    
    public Integer getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public Integer getPositionId() {
		return positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

    public java.util.Date getJoinedAt() {
        return joinedAt;
    }

    public void setJoinedAt(java.util.Date joinedAt) {
        this.joinedAt = joinedAt;
    }

}