package com.oneplatform.cms.dao.entity;

import com.jeesuite.mybatis.core.BaseEntity;
import javax.persistence.*;

/**
 * generated by www.jeesuite.com
 */
@Table(name = "CMS_ARTICLE")
public class CmsArticleEntity extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;
    
    /**
    * @return title 标题
    */
    @Column(name = "title")
    private String title;
    
    /**
    * @return cover 
    */
    @Column(name = "cover")
    private String cover;
    
    /**
    * @return summary 
    */
    @Column(name = "summary")
    private String summary;
    
    /**
    * @return content 内容
    */
    @Column(name = "content")
    private String content;
    
    /**
    * @return categoryId 
    */
    @Column(name = "category_id")
    private Integer categoryId;
    
    /**
    * @return viewCount 浏览数
    */
    @Column(name = "view_count")
    private Integer viewCount;
    
    /**
    * @return commentCount 评论数
    */
    @Column(name = "comment_count")
    private Integer commentCount;
    
    /**
    * @return likeCount 点赞数
    */
    @Column(name = "like_count")
    private Integer likeCount;
    
    /**
    * @return audited 是否审核
    */
    @Column(name = "audited")
    private Boolean audited;
    
    /**
    * @return createdBy 
    */
    @Column(name = "created_by")
    private Integer createdBy;
    
    /**
    * @return createdAt 
    */
    @Column(name = "created_at")
    private java.util.Date createdAt;
    
    /**
    * @return updatedBy 
    */
    @Column(name = "updated_by")
    private Integer updatedBy;
    
    /**
    * @return updatedAt 
    */
    @Column(name = "updated_at")
    private java.util.Date updatedAt;
    

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }
    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public Integer getViewCount() {
        return viewCount;
    }

    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }
    public Integer getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }
    public Integer getLikeCount() {
        return likeCount;
    }

    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
    public Boolean getAudited() {
        return audited;
    }

    public void setAudited(Boolean audited) {
        this.audited = audited;
    }
    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}