package com.oneplatform.cms.controller;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.jeesuite.common.util.AssertUtil;
import com.jeesuite.common.util.BeanUtils;
import com.jeesuite.mybatis.plugin.pagination.Page;
import com.jeesuite.springweb.model.WrapperResponse;
import com.jeesuite.security.client.LoginContext;
import com.oneplatform.base.model.IdParam;

import com.oneplatform.cms.dto.param.CmsArticleQueryParam;
import com.oneplatform.cms.dao.entity.CmsArticleEntity;
import com.oneplatform.cms.dto.param.CmsArticleParam;
import com.oneplatform.cms.service.CmsArticleService;

import io.swagger.annotations.ApiOperation;

/**
 * generated by www.jeesuite.com
 */
@Controller
@RequestMapping("/cmsArticle")
public class CmsArticleController {

    private @Autowired CmsArticleService cmsArticleService;
	
	@ApiOperation(value = "分页查询")
	@RequestMapping(value = "list", method = RequestMethod.POST)
    public @ResponseBody Page<CmsArticleEntity> pageQueryCmsArticles(@RequestBody CmsArticleQueryParam param) {
		Page<CmsArticleEntity> page = cmsArticleService.pageQuery(param,param);
		return page;
	}
	
	@ApiOperation(value = "按id查询")
	@RequestMapping(value = "{id}", method = RequestMethod.GET)
    public @ResponseBody WrapperResponse<CmsArticleEntity> getById(@PathVariable("id") int id) {
		CmsArticleEntity entity = cmsArticleService.findCmsArticleById(id);
		return new WrapperResponse<>(entity);
	}
	
	@ApiOperation(value = "新增")
	@RequestMapping(value = "add", method = RequestMethod.POST)
    public @ResponseBody WrapperResponse<String> addCmsArticle(@RequestBody CmsArticleParam param) {
		CmsArticleEntity entity = BeanUtils.copy(param, CmsArticleEntity.class);
		//entity.setCreatedAt(new Date());
		//entity.setCreatedBy(LoginContext.getIntFormatUserId());
		cmsArticleService.addCmsArticle(entity);
		
		return new WrapperResponse<>();
	}
	
	@ApiOperation(value = "更新")
	@RequestMapping(value = "update", method = RequestMethod.POST)
    public @ResponseBody WrapperResponse<String> updateCmsArticle(@RequestBody CmsArticleParam param) {
		CmsArticleEntity entity = BeanUtils.copy(param, CmsArticleEntity.class);
		//entity.setUpdatedAt(new Date());
		//entity.setUpdatedBy(LoginContext.getIntFormatUserId());
		cmsArticleService.updateCmsArticle(entity);
		
		return new WrapperResponse<>();
	}
	
	@ApiOperation(value = "删除")
	@RequestMapping(value = "delete/{id}", method = RequestMethod.POST)
    public @ResponseBody WrapperResponse<String> deleteCmsArticle(@RequestBody IdParam param) {
		cmsArticleService.deleteCmsArticle(param.getId());
		return new WrapperResponse<>();
	}
	
	
}
